// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ui_preferences.proto

public final class UiPreferences {
  private UiPreferences() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Sorting}
   */
  public enum Sorting
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>A_TO_Z = 0;</code>
     */
    A_TO_Z(0),
    /**
     * <code>Z_TO_A = 1;</code>
     */
    Z_TO_A(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>A_TO_Z = 0;</code>
     */
    public static final int A_TO_Z_VALUE = 0;
    /**
     * <code>Z_TO_A = 1;</code>
     */
    public static final int Z_TO_A_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sorting valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Sorting forNumber(int value) {
      switch (value) {
        case 0: return A_TO_Z;
        case 1: return Z_TO_A;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sorting>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sorting> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sorting>() {
            public Sorting findValueByNumber(int number) {
              return Sorting.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return UiPreferences.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sorting[] VALUES = values();

    public static Sorting valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sorting(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Sorting)
  }

  public interface HomePreferencesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HomePreferences)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Sorting sorting = 1;</code>
     * @return The enum numeric value on the wire for sorting.
     */
    int getSortingValue();
    /**
     * <code>.Sorting sorting = 1;</code>
     * @return The sorting.
     */
    UiPreferences.Sorting getSorting();
  }
  /**
   * Protobuf type {@code HomePreferences}
   */
  public static final class HomePreferences extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HomePreferences)
      HomePreferencesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HomePreferences.newBuilder() to construct.
    private HomePreferences(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HomePreferences() {
      sorting_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HomePreferences();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UiPreferences.internal_static_HomePreferences_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UiPreferences.internal_static_HomePreferences_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UiPreferences.HomePreferences.class, UiPreferences.HomePreferences.Builder.class);
    }

    public static final int SORTING_FIELD_NUMBER = 1;
    private int sorting_;
    /**
     * <code>.Sorting sorting = 1;</code>
     * @return The enum numeric value on the wire for sorting.
     */
    @java.lang.Override public int getSortingValue() {
      return sorting_;
    }
    /**
     * <code>.Sorting sorting = 1;</code>
     * @return The sorting.
     */
    @java.lang.Override public UiPreferences.Sorting getSorting() {
      @SuppressWarnings("deprecation")
      UiPreferences.Sorting result = UiPreferences.Sorting.valueOf(sorting_);
      return result == null ? UiPreferences.Sorting.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sorting_ != UiPreferences.Sorting.A_TO_Z.getNumber()) {
        output.writeEnum(1, sorting_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sorting_ != UiPreferences.Sorting.A_TO_Z.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, sorting_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UiPreferences.HomePreferences)) {
        return super.equals(obj);
      }
      UiPreferences.HomePreferences other = (UiPreferences.HomePreferences) obj;

      if (sorting_ != other.sorting_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SORTING_FIELD_NUMBER;
      hash = (53 * hash) + sorting_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UiPreferences.HomePreferences parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UiPreferences.HomePreferences parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UiPreferences.HomePreferences parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UiPreferences.HomePreferences parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UiPreferences.HomePreferences parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UiPreferences.HomePreferences parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UiPreferences.HomePreferences parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UiPreferences.HomePreferences parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UiPreferences.HomePreferences parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UiPreferences.HomePreferences parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UiPreferences.HomePreferences parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UiPreferences.HomePreferences parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UiPreferences.HomePreferences prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HomePreferences}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HomePreferences)
        UiPreferences.HomePreferencesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UiPreferences.internal_static_HomePreferences_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UiPreferences.internal_static_HomePreferences_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UiPreferences.HomePreferences.class, UiPreferences.HomePreferences.Builder.class);
      }

      // Construct using UiPreferences.HomePreferences.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sorting_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UiPreferences.internal_static_HomePreferences_descriptor;
      }

      @java.lang.Override
      public UiPreferences.HomePreferences getDefaultInstanceForType() {
        return UiPreferences.HomePreferences.getDefaultInstance();
      }

      @java.lang.Override
      public UiPreferences.HomePreferences build() {
        UiPreferences.HomePreferences result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UiPreferences.HomePreferences buildPartial() {
        UiPreferences.HomePreferences result = new UiPreferences.HomePreferences(this);
        result.sorting_ = sorting_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UiPreferences.HomePreferences) {
          return mergeFrom((UiPreferences.HomePreferences)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UiPreferences.HomePreferences other) {
        if (other == UiPreferences.HomePreferences.getDefaultInstance()) return this;
        if (other.sorting_ != 0) {
          setSortingValue(other.getSortingValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sorting_ = input.readEnum();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int sorting_ = 0;
      /**
       * <code>.Sorting sorting = 1;</code>
       * @return The enum numeric value on the wire for sorting.
       */
      @java.lang.Override public int getSortingValue() {
        return sorting_;
      }
      /**
       * <code>.Sorting sorting = 1;</code>
       * @param value The enum numeric value on the wire for sorting to set.
       * @return This builder for chaining.
       */
      public Builder setSortingValue(int value) {
        
        sorting_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Sorting sorting = 1;</code>
       * @return The sorting.
       */
      @java.lang.Override
      public UiPreferences.Sorting getSorting() {
        @SuppressWarnings("deprecation")
        UiPreferences.Sorting result = UiPreferences.Sorting.valueOf(sorting_);
        return result == null ? UiPreferences.Sorting.UNRECOGNIZED : result;
      }
      /**
       * <code>.Sorting sorting = 1;</code>
       * @param value The sorting to set.
       * @return This builder for chaining.
       */
      public Builder setSorting(UiPreferences.Sorting value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sorting_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Sorting sorting = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSorting() {
        
        sorting_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HomePreferences)
    }

    // @@protoc_insertion_point(class_scope:HomePreferences)
    private static final UiPreferences.HomePreferences DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UiPreferences.HomePreferences();
    }

    public static UiPreferences.HomePreferences getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HomePreferences>
        PARSER = new com.google.protobuf.AbstractParser<HomePreferences>() {
      @java.lang.Override
      public HomePreferences parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HomePreferences> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HomePreferences> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UiPreferences.HomePreferences getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HomePreferences_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HomePreferences_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ui_preferences.proto\",\n\017HomePreference" +
      "s\022\031\n\007sorting\030\001 \001(\0162\010.Sorting*!\n\007Sorting\022" +
      "\n\n\006A_TO_Z\020\000\022\n\n\006Z_TO_A\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HomePreferences_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HomePreferences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HomePreferences_descriptor,
        new java.lang.String[] { "Sorting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
